# -*- coding: utf-8 -*-
"""HandPoseTraining.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16Hie6_ZH4buv6NdCNOvxN-XuezR5N3aO
"""

import pandas as pd
import numpy as np
from keras.models import Sequential
from keras.layers import Dense, Flatten
from keras.callbacks import EarlyStopping
from sklearn.model_selection import train_test_split
from tensorflow.keras.models import load_model
from sklearn.metrics import confusion_matrix
import seaborn as sns
import matplotlib.pyplot as plt

#Download Folder
from google.colab import files

#read in data using pandas
train_df = pd.read_csv('drive/MyDrive/Projects/ITR_Project/final_handData.csv')
#check data has been read in properly
print(train_df)

#create a dataframe with all training data except the target column
X = train_df.drop(columns=["0"])
X = X.loc[:, ~X.columns.str.contains('^Unnamed')]

#check that the target variable has been removed
print(X)

X.shape

data_y = train_df["0"]
data_y[0:5]
data_y.shape

X.isnull().sum()

def MultiLabelMaker(y, No_labels):
    train_Y = []
    for i in y:
        labels = np.array([0]*No_labels)
        labels[i] = 1
        train_Y.append(labels)
    return np.array(train_Y)

Y = MultiLabelMaker(data_y, 5)
print(Y[4])

X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.1, random_state=42)

def model(X):
    #create model
    model = Sequential()

    #get number of columns in training data
    n_cols = X.shape[1]

    #add layers to model
    model.add(Flatten(input_shape=(n_cols,)))
    model.add(Dense(80, activation='relu' ))
    model.add(Dense(96, activation='relu'))
    model.add(Dense(128, activation='relu'))
    model.add(Dense(32, activation='relu'))
    model.add(Dense(16, activation='relu'))
    model.add(Dense(5, activation='softmax'))
    return model

model_2 = model(X_train)

#compile model using accuracy to measure model performance
model_2.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

#train model
model_2.fit(X_train, y_train, epochs=50, validation_split=0.2)

prediction = model_2.predict(X_test)

model_2.save("handPose")

!zip -r /content/handPose10.zip /content/handPose
files.download("/content/handPose10.zip")

"""### Model loading"""

# Load the gesture recognizer model
# model = load_model('drive/MyDrive/Projects/ITR_Project/handPose2')
model = load_model('handPose')

# Load class names
f = open('gesture2.names', 'r')
classNames = f.read().split('\n')
f.close()
print(classNames)

model.summary()

prediction = model.predict(X_test)

y_predict = []
for i in prediction:
    y_predict.append(np.argmax(i))
y_predict = np.array(y_predict)

y = []
for i in y_test:
    y.append(np.where(i == 1)[0][0])
y = np.array(y)

#compute the confusion matrix.
cm = confusion_matrix(y,y_predict)

#Plot the confusion matrix.
sns.heatmap(cm,
            annot=True,
            fmt='g',
            xticklabels=['start','Thumbs_up','Arrow','Three_Fingers','stop','Random'],
            yticklabels=['start','Thumbs_up','Arrow','Three_Fingers','stop','Random'])
plt.ylabel('Prediction',fontsize=13)
plt.xlabel('Actual',fontsize=13)
plt.title('Confusion Matrix',fontsize=17)
plt.show()